name: fronticr_empleado
description: App móvil para empleados — marcación de asistencia con geolocalización (ICR).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # networking
  dio: ^5.7.0

  # location + connectivity
  geolocator: ^13.0.1
  connectivity_plus: ^6.1.0

  # local storage (offline queue)
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

  # push notifications
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5

  # formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
